In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\envs\kin\lib\site-packages (1.1.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\user\anaconda3\envs\kin\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\anaconda3\envs\kin\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.15.4 in c:\users\user\anaconda3\envs\kin\lib\site-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\envs\kin\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

In [8]:
import numpy as np
data = np.array([
    [1,'Alice', 30],
    [2,'Bob',25],
    [3,'Charlie',35]])

In [9]:
df =pd.DataFrame(data)

In [10]:
df = pd.DataFrame(data, columns=['ID','Name','Age'])

In [15]:
df= pd.read_csv("C:/Users/User/Desktop/Data/test.csv", header=0, encoding='cp949')

In [16]:
df.shape

(3, 3)

In [23]:
df=pd.read_csv("C:/Users/User/Desktop/Data/국영수.csv",encoding='cp949')

In [24]:
df.shape

(9, 4)

In [25]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='object')

In [26]:
df.dtypes

국어     int64
영어     int64
수학     int64
체육    object
dtype: object

In [27]:
df.describe()

              국어         영어         수학
count   9.000000   9.000000   9.000000
mean   65.888889  65.666667  53.000000
std    17.467430  25.729361  28.583212
min    41.000000  22.000000  13.000000
25%    54.000000  47.000000  21.000000
50%    61.000000  65.000000  54.000000
75%    84.000000  87.000000  78.000000
max    87.000000  98.000000  87.000000

In [28]:
df.head()

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하

In [29]:
df.tail()

   국어  영어  수학 체육
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [30]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [32]:
df['체육'].value_counts()

중    3
상    3
하    2
히    1
Name: 체육, dtype: int64

In [34]:
df['체육'].unique()

array(['상', '중', '하', '히'], dtype=object)

In [35]:
df['체육'].nunique()

4

In [37]:
df["합계"]=df["국어"]+df["영어"]+df["수학"]

In [38]:
df["합계"]

0    159
1    182
2    234
3    159
4    116
5    218
6    240
7    199
8    154
Name: 합계, dtype: int64

In [43]:
df = df.drop(['체육'], axis=1)

In [44]:
df

   국어  영어  수학   합계
0  50  88  21  159
1  41  87  54  182
2  85  65  84  234
3  61  85  13  159
4  54  41  21  116
5  84  47  87  218
6  77  98  65  240
7  87  58  54  199
8  54  22  78  154

In [50]:
columns = ['column_a','column_b','column_c']

In [51]:
columns

['column_a', 'column_b', 'column_c']

In [60]:
data={
    'A':[1,2,3,4],
    'B':[4.1,3.5,2.1,5.7],
    'C':['one','two','three','four']
}

In [62]:
df = pd.DataFrame(data)

In [63]:
df['A'].astype('category')

0    1
1    2
2    3
3    4
Name: A, dtype: category
Categories (4, int64): [1, 2, 3, 4]

In [64]:
df['A']=df['A'].astype('str')

In [65]:
df['A'].astype('category')

0    1
1    2
2    3
3    4
Name: A, dtype: category
Categories (4, object): ['1', '2', '3', '4']

In [66]:
df = df.rename(columns={'old_name':'new_name'})

In [69]:
df = df.rename(columns={
    'old_name1':'new_name1',
    'old_name2':'new_name2',
    'old_name3':'new_name3'
})

In [70]:
df

   A    B      C
0  1  4.1    one
1  2  3.5    two
2  3  2.1  three
3  4  5.7   four

In [73]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dog']
}

In [74]:
df = pd.DataFrame(data)

In [75]:
A=df.select_dtypes(include=["number"]).columns

In [76]:
B=df.select_dtypes(include=['object','category']).columns

In [77]:
df[A].fillna(df[A].median())

   Numeric1  Numeric2
0       1.0       5.0
1       3.0       6.0
2       3.0       6.0
3       4.0       8.2

In [78]:
A

Index(['Numeric1', 'Numeric2'], dtype='object')

In [79]:
df[A].fillna(df[A].mean())

   Numeric1  Numeric2
0  1.000000       5.0
1  2.666667       6.0
2  3.000000       6.4
3  4.000000       8.2

In [80]:
df.fillna(df.median)

,Numeric1,Numeric2,Category
0,1,5,dog
1,<bound method DataFrame.median of Numeric1 ...,6,<bound method DataFrame.median of Numeric1 ...
2,3,<bound method DataFrame.median of Numeric1 ...,cat
3,4,8.2,dog

In [81]:
df1=pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3']
})

In [82]:
df2=pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5']
})

In [83]:
pd.concat([df1,df2], axis=0)

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
0  a2  b2  c2
1  a3  b3  c3
2  a4  b4  c4
3  a5  b5  c5

In [84]:
pd.concat([df1,df2], axis=1)

    a   b   c   a   b   c
0  a0  b0  c0  a2  b2  c2
1  a1  b1  c1  a3  b3  c3
2  a2  b2  c2  a4  b4  c4
3  a3  b3  c3  a5  b5  c5

In [85]:
pd.concat([df[A],df[B]], axis=0)

   Numeric1  Numeric2 Category
0       1.0       5.0      NaN
1       NaN       6.0      NaN
2       3.0       NaN      NaN
3       4.0       8.2      NaN
0       NaN       NaN      dog
1       NaN       NaN      NaN
2       NaN       NaN      cat
3       NaN       NaN      dog

In [86]:
pd.concat([df[A],df[B]], axis=1)

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [87]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dog']
}

In [88]:
df = pd.DataFrame(data)

In [89]:
df[0:2]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN

In [90]:
df[:2]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN

In [91]:
df[(df['Numeric2']>=6)&(df['Numeric2']<=10)]
df[(df['Numeric2']>=6)|(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [92]:
df[(df['Numeric2']>=6)&(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [94]:
df[(df['Numeric2']>=6)|(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog